# Generated by Django 3.0.5 on 2020-07-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentEmail', models.EmailField(max_length=254)),
                ('currentName', models.CharField(max_length=100)),
                ('currentPathToRead', models.TextField()),
                ('currentPathToWrite', models.TextField()),
                ('prevComputeIndex', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
